theme: jekyll-theme-minimal
title: Welcome to Manya's homepage!
logo: assests/img/headshot.png

social-network-links:
  email: "manyaa.wadhwa@gmail.com"
  linkedin: manya-wadhwa-9798a79a
  instagram: manya.wadhwa

share-links-active:
  instagram: true
  linkedin: true
