title: Manya Wadhwa
logo: "assests/img/headshot.png"
name: Manya Wadhwa
description: Research Engineer @ Goldman Sachs R&D
email: manyaa.wadhwa@gmail.com

linkedin_username: https://www.linkedin.com/in/manya-wadhwa-9798a79a/
aboutme_username:
instagram_username: https://instagram.com/manya.wadhwa

theme: jekyll-theme-minimal

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-remote-theme
